### ISSUE TITLE
Get data from public ip

### ISSUE THREAD

**Issue by marcemarin** [ipinfo/laravel#12]
this is the response i get when i run $ request-> ipinfo

![asdasd](https://user-images.githubusercontent.com/7118089/103647797-9d425680-4f3a-11eb-9d5e-331e4a58f32e.png)

How can I get the data from my public ip?

**Comment by UmanShahzad** [comment]
@marcemarin If you want your public IP, this is the wrong package - use the PHP package at https://github.com/ipinfo/php.

This package is meant to retrieve details automatically for the client IP of the request. It will not make requests for any random IP you wish, which is what the underlying PHP package is for.

In this case the "client IP" was "172.18.0.1". If an outside user had the IP "1.2.3.4" and hit your Laravel endpoint, you'd see that IP instead.

**Comment by marcemarin** [comment]
But in the docs you do "$ip_address = '216.239.36.21';", i need to get that ip from the client request

**Comment by coderholic** [comment]
172.18.0.1 is a bogon

**Comment by marcemarin** [comment]
Thanks a lot guys, it works perfect

**Comment by UmanShahzad** [comment]
It's definitely a matter of making requests to a dev server over the local network.

@marcemarin To elaborate a bit more, you need to use the PHP package and input the IP you want to look up within your request handler. This Laravel package is a simple wrapper over the PHP package and is dedicated to one thing: automating the lookup of the _client IP_.
