### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by marcemarin** [ipinfo/laravel#14]
Hi, i get this error not every tme
count(): Parameter must be an array or an object that implements Countable
Any idea?
Thanks.

**Comment by UmanShahzad** [comment]
@marcemarin Hey buddy, I merged #15 which should fix this.

I just want to confirm with you - you were using a cache, and it had items in it when your app started, right? This is the only possible scenario where this could have happened AFAIK.

**Comment by marcemarin** [comment]
Thank you so much, yes we do use a cache! The fix also cover library https://github.com/ipinfo/php?

**Comment by UmanShahzad** [comment]
@marcemarin Thanks, I didn't realize the PHP SDK is actually using the same method, and has the same bug. I've fixed it there too with https://github.com/ipinfo/php/pull/27 and updated the [Laravel SDK to v2.1.2](https://packagist.org/packages/ipinfo/ipinfolaravel#v2.1.2) to use the latest PHP SDK with that fix.
