### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by RyonMB** [ipinfo/laravel#28]
I would like the option to easily handle exceptions. Sometimes ipinfo throws a random exception (when the service is temporarily unavailable for example). But it results immediately in production a 500 error.

I would like the option to set a parameter that exceptions can be ignored and logged. So the application still continues working. And that $request->ipinfo just returns an empty object.

Currently there is no easy way to handle those exceptions.

**Comment by UmanShahzad** [comment]
Thanks for the report @RyonMB!

Please upgrade to v2.2.0 and follow the directions at https://github.com/ipinfo/laravel#suppressing-exceptions.
