### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by netbuild** [ipinfo/laravel#40]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sabre/cache[1.0.0, ..., 1.0.4] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - sabre/cache 1.0.2 requires php ^7.1 -> your php version (8.0.20) does not satisfy that requirement.
    - ipinfo/ipinfolaravel v2.4.0 requires ipinfo/ipinfo ^2.3.1 -> satisfiable by ipinfo/ipinfo[v2.3.1, 2.3.x-dev].
    - ipinfo/ipinfo[v2.3.1, ..., 2.3.x-dev] require sabre/cache ^1.0 -> satisfiable by sabre/cache[1.0.0, ..., 1.0.4].
    - Root composer.json requires ipinfo/ipinfolaravel ^2.4 -> satisfiable by ipinfo/ipinfolaravel[v2.4.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ipinfo/ipinfolaravel:*" to figure out if any version is installable, or "composer require ipinfo/ipinfolaravel:^2.1" if you know which you need.

**Comment by UmanShahzad** [comment]
@rm-Umar can you check this out.

**Comment by rm-Umar** [comment]
@UmanShahzad not an issue from our end, `sabre/cache` @netbuild is using PHP 8 and `sabre/cache` added `PHP 8` support in version `1.0.3` https://github.com/sabre-io/cache/pull/25  and here it's installing `version 1.0.2`. @netbuild should install `version 1.0.3 > ` to resolve this issue. You can do that by running the command `composer require sabre/cache:1.0.3` and then installing the ipinfo package again and it'll fix your issue

**Comment by rm-Umar** [comment]
@UmanShahzad this is not an issue from our package. We are using `sabre/cache` in our `php` library and `sabre/cache` users `psr/simple-cache:1`. https://github.com/sabre-io/cache/blob/8120da1320b4e0288fa2ff49cebb1a8221641faa/composer.json#L18. The laravel framework is using `psr/simple-cache:3` by default but it supports `1.0 || 2.0 || 3.0` as well. So when someone creates a fresh laravel project it locks the `psr/simple-cache` version to 3 in `composer.lock` file. The simple solution for this is to change the `psr-simple-cache` version in `composer.lock` or just remove the lock file and install our package and composer will automatically create a new lock file with required versions.
