### ISSUE TITLE
Get ip of the user

### ISSUE THREAD

**Issue by geresy** [ipinfo/laravel#6]
With: $request->ipinfo->country I get the details of the server not of the user. 

How do I pass $request->getClientIp(); to ipinfo?

**Comment by coderholic** [comment]
Yeah looks like it could be a bug. I believe we should be passing the ip from the request in here: https://github.com/ipinfo/laravel/blob/master/src/ipinfolaravel.php#L47

**Comment by geresy** [comment]
Thanks for pointing me in the right direction, I passed the IP in the getDetails functions and it now works as intended. 
![image](https://user-images.githubusercontent.com/3873509/79302799-03db9c00-7ef6-11ea-92b7-97ddac6fa809.png)

**Comment by UmanShahzad** [comment]
We'll address this shortly. Sorry for the late response.

**Comment by UmanShahzad** [comment]
See https://packagist.org/packages/ipinfo/ipinfolaravel#v2.0.0.
